language: go
sudo: false
go:
  - 1.15
  - tip
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test -v
branches:
  only:
    - master
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username tsuyoshiwada --token $GITHUB_TOKEN --replace `grep 'Version =' version.go | sed -E 's/.*"(.+)"$$/\1/'` dist/
